// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwqrU3biJJwV3GyDlpkSqxdZoU3BtgDWA',
    appId: '1:33382936467:web:8ac37033d076ed0e024266',
    messagingSenderId: '33382936467',
    projectId: 'campusdelivery',
    authDomain: 'campusdelivery.firebaseapp.com',
    storageBucket: 'campusdelivery.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBruNWmDp-64wCnP0tNnBy-zCgg-4n2Mwk',
    appId: '1:33382936467:android:8f6eda23ece7da4a024266',
    messagingSenderId: '33382936467',
    projectId: 'campusdelivery',
    storageBucket: 'campusdelivery.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjqtJGozLe9ip6FdRQotiIjoLOhVYAPeE',
    appId: '1:33382936467:ios:a036a21dcfbbbe79024266',
    messagingSenderId: '33382936467',
    projectId: 'campusdelivery',
    storageBucket: 'campusdelivery.firebasestorage.app',
    iosBundleId: 'com.campus.bot.campusDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjqtJGozLe9ip6FdRQotiIjoLOhVYAPeE',
    appId: '1:33382936467:ios:a036a21dcfbbbe79024266',
    messagingSenderId: '33382936467',
    projectId: 'campusdelivery',
    storageBucket: 'campusdelivery.firebasestorage.app',
    iosBundleId: 'com.campus.bot.campusDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwqrU3biJJwV3GyDlpkSqxdZoU3BtgDWA',
    appId: '1:33382936467:web:3ae26628deea712c024266',
    messagingSenderId: '33382936467',
    projectId: 'campusdelivery',
    authDomain: 'campusdelivery.firebaseapp.com',
    storageBucket: 'campusdelivery.firebasestorage.app',
  );
}
